import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";
import Header from "./components/common/header";
import Footer from "./components/common/footer";
import { getOther } from "@/sanity/utils/fetchOther";

const roboto = Roboto({
  weight: ["100", "400", "500", "700", "900"],
  style: "normal",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getOther();
  const otherData = (data as any[]).filter((d) => d._type === "other")[0];
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <div className="grow">{children}</div>
          <Footer data={otherData} />
        </div>
      </body>
    </html>
  );
}
